# Generated by Django 4.0.6 on 2022-07-29 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(default='', max_length=25)),
                ('department_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.departments')),
            ],
        ),
        migrations.CreateModel(
            name='patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25)),
                ('fathername', models.CharField(default='', max_length=25)),
                ('phoneno', models.IntegerField()),
                ('emailid', models.EmailField(default='', max_length=25)),
                ('address', models.CharField(default='', max_length=25)),
                ('gender', models.CharField(default='', max_length=25)),
                ('age', models.IntegerField()),
                ('familymember', models.CharField(default='', max_length=25)),
                ('relation', models.CharField(default='', max_length=25)),
                ('dob', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='room_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField()),
                ('ac', models.CharField(default='', max_length=25)),
                ('tv', models.CharField(default='', max_length=25)),
                ('sharing', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=25)),
                ('password', models.CharField(default='', max_length=25)),
                ('status', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=25)),
                ('amount', models.CharField(default='', max_length=25)),
                ('checkout', models.CharField(default='', max_length=25)),
                ('history', models.CharField(default='', max_length=25)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.doctors')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patients')),
                ('roomservices', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.room_services')),
            ],
        ),
    ]
