# Generated by Django 4.0.6 on 2023-04-18 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('age', models.CharField(max_length=4)),
                ('date', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'Book_Appointment',
            },
        ),
        migrations.RemoveField(
            model_name='registration',
            name='roomservices',
        ),
        migrations.AddField(
            model_name='registration',
            name='roomservices_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.room_services'),
        ),
    ]
