# Generated by Django 4.0.6 on 2023-04-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_book_appointment_remove_registration_roomservices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='roomservices_id',
        ),
        migrations.AddField(
            model_name='book_appointment',
            name='treatment_for',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='departments',
        ),
        migrations.DeleteModel(
            name='doctors',
        ),
        migrations.DeleteModel(
            name='patients',
        ),
        migrations.DeleteModel(
            name='registration',
        ),
        migrations.DeleteModel(
            name='room_services',
        ),
    ]
